### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by wtr850** [Pranshu258/Deep_Image_Captioning#5]
Thank you for your nice work on the codes!
I have a simple question about the three .pt files in code/models/ .
In what condition were they trained on? With what kind of dataset and How many training images?

**Comment by Pranshu258** [comment]
They were trained from scratch on a subset of the MSCOCO dataset (50000 images) on a GPU powered machine. 
The training code is provided in the Jupyter notebook

**Comment by wtr850** [comment]
Got it. Thanks for answering :)
